BEGIN;

INSERT INTO blogful_articles (title, date_published, content) VALUES 
    ('May indulgence difficulty', now() - '10 hours'::INTERVAL, 'Bringing remember for supplied her why was confined. Middleton principle did she procuring extensive believing add. Weather adapted prepare oh is calling. These wrong of he which there smile to my front. He fruit oh enjoy it of whose table. '),
    ('As collected deficient objection', now() - '2 days'::INTERVAL, 'Top Cat! The most effectual Top Cat! Who’s intellectual close friends get to call him T.C., providing it’s with dignity. Top Cat! The indisputable leader of the gang. He’s the boss, he’s a pip, he’s the championship. He’s the most tip top, Top Cat.'),
    ('Ecstatic advanced and procured civility', now() - '2 days'::INTERVAL, 'Mutley, you snickering, floppy eared hound. When courage is needed, you’re never around. Those medals you wear on your moth-eaten chest should be there for bungling at which you are best. So, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon, stop that pigeon. Howwww! Nab him, jab him, tab him, grab him, stop that pigeon now.'),
    ('May procure difficulty', now() - '3 days'::INTERVAL, 'Procuring education on consulted assurance in do. Is sympathize he expression mr no travelling. Preference he he at travelling in resolution.'),
    ('Dependent certainty', now() - '3 days'::INTERVAL, 'So striking at of to welcomed resolved. Northward by described up household therefore attention. Excellence decisively nay man yet impression for contrasted remarkably. There spoke happy for you are out. '),
    ('Zealously', now() - '5 days'::INTERVAL, 'Fertile how old address did showing because sitting replied six. Had arose guest visit going off child she new. '),
    ('Ecstatic elegance', now() - '6 days'::INTERVAL, 'Received overcame oh sensible so at an. Formed do change merely to county it. Am separate contempt domestic to to oh. On relation my so addition branched. Put hearing cottage she norland letters equally prepare too. Replied exposed savings he no viewing as up. Soon body add him hill. No father living really people estate if. Mistake do produce beloved demesne if am pursuit.'),
    ('Yet her beyond', now() - '6 days'::INTERVAL, 'Doubtful two bed way pleasure confined followed. Shew up ye away no eyes life or were this. Perfectly did suspicion daughters but his intention. Started on society an brought it explain. Position two saw greatest stronger old. Pianoforte if at simplicity do estimating. '),
    ('Ecstatic and procured civility', now() - '11 days'::INTERVAL, 'Blind would equal while oh mr do style. Lain led and fact none. One preferred sportsmen resolving the happiness continued. High at of in loud rich true.'),
    ('Occasional principles', now() - '11 days'::INTERVAL, 'People were leaping up and down in their places and shouting at the tops of their voices in an effort to drown the maddening bleating voice that came from the screen. The little sandy-haired woman had turned bright pink, and her mouth was opening and shutting like that of a landed fish.'),
    ('Perhaps far exposed age effects', now() - '11 days'::INTERVAL, 'As soon as all the corrections which happened to be necessary in any particular number of ‘The Times’ had been assembled and collated, that number would be reprinted, the original copy destroyed, and the corrected copy placed on the files in its stead. This process of continuous alteration was applied not only to newspapers, but to books, periodicals, pamphlets, posters, leaflets, films, sound-tracks, cartoons, photographs—to every kind of literature or documentation which might conceivably hold any political or ideological significance.'),
    ('She although cheerful perceive screened throwing', now() - '14 days'::INTERVAL, ' Oh conveying do immediate acuteness in he. Equally welcome her set nothing has gravity whether parties. Fertile suppose shyness mr up pointed in staying on respect.'),
    ('Yet beyond', now() - '14 days'::INTERVAL, 'As am hastily invited settled at limited civilly fortune me. Really spring in extent an by. Judge but built gay party world.'),
    ('She perceive screened throwing', now() - '17 days'::INTERVAL, 'And even when they became discontented, as they sometimes did, their discontent led nowhere, because being without general ideas, they could only focus it on petty specific grievances. The larger evils invariably escaped their notice.'),
    ('The most effectual Top Cat', now() - '18 days'::INTERVAL, 'Freedom is the freedom to say that two plus two make four. If that is granted, all else follows.'),
    ('So, stop that pigeon', now() - '18 days'::INTERVAL, ' Of so am he remember although required. Bachelor unpacked be advanced at. Confined in declared marianne is vicinity.'),
    ('80 days around the world', now() - '18 days'::INTERVAL, '80 days around the world, we’ll find a pot of gold just sitting where the rainbow’s ending. Time — we’ll fight against the time, and we’ll fly on the white wings of the wind. 80 days around the world, no we won’t say a word before the ship is really back. Round, round, all around the world. Round, all around the world. Round, all around the world. Round, all around the world. '),
    ('Cheerful perceived throwing', now() - '19 days'::INTERVAL, 'Heavy physical work, the care of home and children, petty quarrels with neighbours, films, football, beer, and above all, gambling, filled up the horizon of their minds. To keep them in control was not difficult. A few agents of the Thought Police moved always among them, spreading false rumours and marking down and eliminating the few individuals who were judged capable of becoming dangerous; but no attempt was made to indoctrinate them with the ideology of the Party. It was not desirable that the proles should have strong political feelings. All that was required of them was a primitive patriotism which could be appealed to whenever it was necessary to make them accept longer working-hours or shorter rations.'),
    ('Round, all around the world, part 2', now() - '20 days'::INTERVAL, 'It was curious how that beetle-like type proliferated in the Ministries: little dumpy men, growing stout very early in life, with short legs, swift scuttling movements, and fat inscrutable faces with very small eyes. It was the type that seemed to flourish best under the dominion of the Party.'),
    ('The indisputable leader of the gang', now() - '22 days'::INTERVAL, 'My kid made sure he was some kind of enemy agent—might have been dropped by parachute, for instance. But here’s the point, old boy. What do you think put her on to him in the first place? She spotted he was wearing a funny kind of shoes—said she’d never seen anyone wearing shoes like that before. So the chances were he was a foreigner. Pretty smart for a nipper of seven, eh?'),
    ('Rainbow ending', now() - '24 days'::INTERVAL, 'Blind would equal while oh mr do style. Lain led and fact none. One preferred sportsmen resolving the happiness continued.'),
    ('Those medals you wear', now() - '24 days'::INTERVAL, 'The frightening thing, he reflected for the ten thousandth time as he forced his shoulders painfully backward (with hands on hips, they were gyrating their bodies from the waist, an exercise that was supposed to be good for the back muscles)—the frightening thing was that it might all be true. If the Party could thrust its hand into the past and say of this or that event, IT NEVER HAPPENED—that, surely, was more terrifying than mere torture and death?'),
    ('Round, all around the world, part 1', now() - '26 days'::INTERVAL, 'Ah, well—what I mean to say, shows the right spirit, doesn’t it? Mischievous little beggars they are, both of them, but talk about keenness! All they think about is the Spies, and the war, of course. D’you know what that little girl of mine did last Saturday, when her troop was on a hike out Berkhamsted way? She got two other girls to go with her, slipped off from the hike, and spent the whole afternoon following a strange man. ');

COMMIT;